### ISSUE TITLE
👋 Hello, awsome project!

### ISSUE THREAD

**Issue by jovemexausto** [Shellomo/vscode-ext-devfocus-pomodoro#1]
Hey there, ADHD dev here—this extension is perfect for me! Would love to contribute (in between hyperfocus sprints). Point me if there's something I can help! 🚀

Cheers,

**Comment by Shellomo** [comment]
Hi Marcus,

Thanks for the kind words and your interest in contributing! 🚀

If you’re up for it, adding a dashboard to display the statistics would be an awesome feature. The data is already being kept, so it’s just about presenting it. Let me know if you’d like to tackle this!

Cheers,

**Comment by jovemexausto** [comment]
Hi Shellomo,

I’d be thrilled to contribute, particularly to the dashboard feature! I'll start looking into it right away. If there are any specific requirements, ideas, or directions you'd like me to follow, please let me know.

I may reach out with questions as I progress, but I’m excited to collaborate and bring this to life.

Looking forward to making it happen!

Cheers,
